version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: "circleci/openjdk:8"
    steps:
      - checkout
      - run: bundle exec middleman build
      - run: docker build --rm=false -t alexec/web:latest .
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push alexec/web
      - run: "curl -fv -u $CIRCLE_TOKEN: -X POST -d '{\"build_parameters\": {\"COMPONENT\": \"web\"}}' -H 'Content-Type: application/json' https://circleci.com/api/v1.1/project/github/phoebus-games/deploy/tree/master"
