version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/ruby:2.4.1-node
    steps:
      - checkout
      - type: cache-restore
        key: bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - type: cache-save
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      - run: bundle exec middleman build
      - setup_remote_docker
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --rm=false -t alexec/web:$CIRCLE_SHA1 .
      - run: docker push alexec/web
      - run: ./deploy.sh
      - run: "curl -f -u $CIRCLE_TOKEN: -X POST https://circleci.com/api/v1.1/project/github/phoebus-games/roulette-assets-default/tree/master"
      - run: "curl -f -u $CIRCLE_TOKEN: -X POST https://circleci.com/api/v1.1/project/github/phoebus-games/classic-slot-assets-default/tree/master"
